import Head from "next/head";
import Navbar from "@/components/Navbar";
import Blog from "@/components/Blog";
import { BlogProps } from "@/types";
import Blogs from "@/components/Blogs";
import { fetchBlogsData } from "@/utils";
interface HomeProps {
  data: BlogProps[];
}

export default function Home({ data }: HomeProps) {
  return (
    <>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Blogs data={data} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const dataReceive = await fetchBlogsData();
  return {
    props: {
      data: dataReceive,
    },
  };
}
